#!/bin/sh
set -e

systemctl daemon-reload
systemctl disable dhcpcd.service
systemctl enable dhcpcd.service

systemctl stop lora-gateway-bridge.service
systemctl stop packet-forwarder.service
systemctl disable lora-gateway-bridge.service
systemctl disable packet-forwarder.service

delgroup --system sdr
deluser --system lora

exit 0
