#!/bin/sh

addgroup --system sdr
adduser --system --group --no-create-home lora
systemctl enable lora-gateway-bridge.service
systemctl enable packet-forwarder.service

udevadm control --reload-rules

exit 0
