#!/bin/sh

addgroup --system sdr
adduser --system --group --no-create-home lora
adduser lora gpio
adduser lora spi

systemctl daemon-reload
systemctl disable dhcpcd.service
systemctl enable dhcpcd.service

systemctl enable lora-gateway-bridge.service
systemctl enable packet-forwarder.service
systemctl start lora-gateway-bridge.service
systemctl start packet-forwarder.service

udevadm control --reload-rules

exit 0
